spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emojiquizapp
    username: root
    password: Adedorcas64#

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
